matrix:
  include:
  - os: linux
    python: 2.7
    env: PYTHON_VERSION=2.7
  - os: linux
    python: 3.3
    env: PYTHON_VERSION=3.3
  - os: linux
    python: 3.4
    env: PYTHON_VERSION=3.4
  - os: linux
    python: 3.5
    env: PYTHON_VERSION=3.5
  - os: linux                                                                   
    python: 3.6                                                                 
    env: PYTHON_VERSION=3.6       
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=2.7
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.3
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.4
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.5
  - os: osx                                                                     
    language: generic                                                           
    env:                                                                        
    - PYTHON_VERSION=3.6  

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-4.0.5-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-4.0.5-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda install --yes python=$PYTHON_VERSION Cython
  - python --version
  - python setup.py build_ext --inplace

script:
  - python test_script.py

