matrix:
  include:
#  - os: linux
#    python: 2.7
#    env: PYTHON_VERSION=2.7
#  - os: linux
#    python: 3.3
#    env: PYTHON_VERSION=3.3
#  - os: linux
#    python: 3.4
#    env: PYTHON_VERSION=3.4
#  - os: linux
#    python: 3.5
#    env: PYTHON_VERSION=3.5
#  - os: linux                                                                   
#    python: 3.6                                                                 
#    env: PYTHON_VERSION=3.6       
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=2.7
#  - os: osx
#    language: generic
#    env:
#    - PYTHON_VERSION=3.3
#  - os: osx
#    language: generic
#    env:
#    - PYTHON_VERSION=3.4
#  - os: osx
#    language: generic
#    env:
#    - PYTHON_VERSION=3.5
#  - os: osx                                                                     
#    language: generic                                                           
#    env:                                                                        
#    - PYTHON_VERSION=3.6  
compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-4.0.5-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-4.0.5-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://prdownloads.sourceforge.net/hpc/gcc-6.3-bin.tar.gz -O gcc.tar.gz; gunzip gcc.tar.gz; sudo tar -xvf gcc.tar -C /; export PATH="/usr/local/bin:$PATH"; fi
  - echo $PATH
  - export PATH="$HOME/miniconda/bin:$PATH"
  - echo $PATH
  - which gcc
  - gcc --version

install:
  - conda install --yes python=$PYTHON_VERSION pandas Cython
  - python --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py build_ext --inplace; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py build_ext --inplace; fi

script:
  - python test_script.py
